services:
  - type: web
    name: email-tracking-pixel
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: email-tracker-db
          property: connectionString
      - key: BASE_URL
        sync: false
